name: practice
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.5
  badges: ^3.1.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.2
  http: ^1.5.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  fluttertoast: ^8.2.12
  go_router: ^16.0.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  firebase_messaging: ^15.2.10
  timeago: ^3.7.1
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
