// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1m-MRAisVmEM86R-6B_D_E8hTGlylUw',
    appId: '1:901930679991:web:3fd678414b113586869732',
    messagingSenderId: '901930679991',
    projectId: 'flutter-practice-a8ae7',
    authDomain: 'flutter-practice-a8ae7.firebaseapp.com',
    storageBucket: 'flutter-practice-a8ae7.firebasestorage.app',
    measurementId: 'G-8M7G3FDETH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFmf0a4RCQZ5cnGSKFt8sKTJMumBxJwQ',
    appId: '1:901930679991:android:f4d4c22a90c2bdd9869732',
    messagingSenderId: '901930679991',
    projectId: 'flutter-practice-a8ae7',
    storageBucket: 'flutter-practice-a8ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5bYiDcgSE9EqUFhpVGqg3tqZbEXPfqxE',
    appId: '1:901930679991:ios:d852c0fbb76987d3869732',
    messagingSenderId: '901930679991',
    projectId: 'flutter-practice-a8ae7',
    storageBucket: 'flutter-practice-a8ae7.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5bYiDcgSE9EqUFhpVGqg3tqZbEXPfqxE',
    appId: '1:901930679991:ios:d852c0fbb76987d3869732',
    messagingSenderId: '901930679991',
    projectId: 'flutter-practice-a8ae7',
    storageBucket: 'flutter-practice-a8ae7.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1m-MRAisVmEM86R-6B_D_E8hTGlylUw',
    appId: '1:901930679991:web:9f8c6a49e745bbd5869732',
    messagingSenderId: '901930679991',
    projectId: 'flutter-practice-a8ae7',
    authDomain: 'flutter-practice-a8ae7.firebaseapp.com',
    storageBucket: 'flutter-practice-a8ae7.firebasestorage.app',
    measurementId: 'G-C9MZ9FHJE4',
  );
}
